[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-motde"
version = "0.1.0"

[project.entry-points."endstone"]
motde = "endstone_motde:Motde"
